#!/bin/sh
cd "${0%/*}"
cd macos
read -p "Enter a platform and hit enter [opengl|metal] : " plaf
java -XstartOnFirstThread -Djava.library.path=. -Xmx1G -Xms1G -jar ../test.jar --debug --dev-assets ../assets_dev --platform $plaf
